# Generated by Django 5.2.4 on 2025-12-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepageimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='infopagecontent',
            options={'verbose_name': 'Info Page Content', 'verbose_name_plural': 'Info Page Content'},
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
